accounts/urls.py

from django.conf.urls import url, include
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^gallery-register/$', views.gallery_register, name = 'gallery_register'),
    url(r'^gallery-login/', views.gallery_login, name = 'gallery_login'),
    url(r'^gallery-logout/', views.gallery_logout, name = 'gallery_logout'),
]

gallery/urls.py

from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'gallery'

urlpatterns = [
    url(r'^$', views.all_images, name = 'all_images'),    
    url(r'^new-gallery/$', views.new_gallery, name = 'new_gallery'),    
]

progal/urls.py

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.welcome, name = 'welcome'),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^account/', include('accounts.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

gallery/models.py

from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

class Gallery(models.Model):
	name = models.CharField(max_length = 100)
	category = models.CharField(max_length = 100)
	slug = models.SlugField()
	image = models.ImageField(default = 'default.png', blank = True)
	date = models.DateTimeField(auto_now_add = True)
	user = models.ForeignKey(User, default = None)

gallery/forms.py
from django import forms
from . import models

class createGalleryForm(forms.ModelForm):
	class Meta:
		model = models.Gallery
		fields = ['name','category','slug','image']

accounts/views.py

from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def gallery_register(request):
	title = 'User Register'
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('accounts:gallery_login')
	else:
		form = UserCreationForm()
	data = {
		'title' : title,
		'form' : form
	}
	return render(request, 'accounts/gallery_register.html', data)			

def gallery_login(request):
	title = 'User Login'
	if request.method == 'POST':
		form = AuthenticationForm(data = request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
		return redirect('gallery:all_images')
	else:
		form = AuthenticationForm()
	data = {
		'title' : title,
		'form' : form
	}
	return render(request, 'accounts/gallery_login.html', data)			 

def gallery_logout(request):
	logout(request)
	return redirect('accounts:gallery_login')

gallery/views.py

from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Gallery
from . import forms
from django.contrib.auth.decorators import login_required

@login_required(login_url = '/account/gallery-login')
def all_images(request):
	title = 'Gallery'
	all_images = Gallery.objects.all().filter(user = request.user)
	data = {
		'title' : title,
		'all_images' : all_images
	}
	return render(request, 'gallery/all_images.html', data)


@login_required(login_url = '/account/gallery-login')
def new_gallery(request):
	title = 'New Gallery'
	if request.method == "POST":
		form = forms.createGalleryForm(request.POST, request.FILES)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
			return redirect('gallery:all_images')
	else:
		form = forms.createGalleryForm()	
	data = {
		'title' : title,
		'form' : form
	}
	return render(request, 'gallery/new_gallery.html', data)	


progal/views.py

from django.http import HttpResponse
from django.shortcuts import render


def welcome(request):
	title = 'Home'
	data = {
		'title' : title
	}
	return render(request, 'welcome.html', data)

accounts/templates/accounts/gallery_login.html
{% extends 'layout.html' %}
{% load bootstrap %}

{% block content %}
	<div id="login-part">
		<div class="container">
			<h2>Login</h2>
			<div class="divider"></div>
			<div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-xs-12">
				<div class="login-content">
					<form class="login-form" method="post" action="{% url 'accounts:gallery_login' %}">
						{% csrf_token %}
						{{ form | bootstrap }}
						<div class="form-group col-lg-8 col-md-8 col-sm-8 col-xs-8">
							<input type="submit" class="form-control btn btn-success" value="Login">
						</div>
					</form>
				</div>	
			</div>
		</div>
	</div>		 
{% endblock %}

accounts/templates/accounts/gallery_register.html
{% extends 'layout.html' %}
<!-- {% load bootstrap %} -->

{% block content %}
	<div id="register-part">
		<div class="container">
			<h2>Register</h2>
			<div class="divider"></div>
			<div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-xs-12">	
				<div class="register-content">	
					<form class="register-form" method="post" action="{% url 'accounts:gallery_register' %}">
						{% csrf_token %}
						<!-- {{ form | bootstrap }} -->
						{% for field in form %}
				            <div class="form-group has-errors text-danger small">
				                {{field.errors}}
				            </div>
				            <div class="form-group">
				                {{ field.label_tag }} 
				                {{ field }}
				            </div>
			            {% endfor %}
						<div class="form-group col-lg-8 col-md-8 col-sm-8 col-xs-8">
							<input type="submit" class="form-control btn btn-success" value="Register">
						</div>
					</form>
				</div>
			</div>		
		</div>
	</div>		 
{% endblock %}

gallery/templates/gallery/all_images.html
{% extends 'layout.html' %}

{% block content %}
<div id="gallery-part">
	<div class="container">
		<h2>Welcome To All Images</h2>
		{% for gallery in all_images %}
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
				<div class="gallery-content">
					<a href="{{ gallery.image.url }}">
						<img src="{{ gallery.image.url }}" class="img-responsive" alt="{{ gallery.name }}">
						<h2>{{ gallery.name }}</h2>
						<h4>{{ gallery.category }}</h4>
					</a>
				</div>		
			</div>	
		{% endfor %}	
	</div>	
</div>
{% endblock %}

gallery/templates/gallery/new_gallery.html
{% extends 'layout.html' %}
{% load bootstrap %}

{% block content %}
	<div id="new-gallery-part">
		<div class="container">
			<h2>Create Gallery</h2>
			<div class="divider"></div>
			<div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-xs-12">
				<div class="new-gallery-content">
					<form class="new-gallery-form" method="post" action="{% url 'gallery:new_gallery' %}" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form | bootstrap }}
						<div class="form-group col-lg-8 col-md-8 col-sm-8 col-xs-8">
							<input type="submit" class="form-control btn btn-success" value="Create">
						</div>
					</form>
				</div>	
			</div>
		</div>
	</div>		 
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }} - UrGallery</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/lightbox.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/progalcss.css' %}">
</head>
<body>
	<!-- Header Part -->
	<div id="header-part">
		<nav class="navbar navbar-custom navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	                	<span class="sr-only">Toggle navigation</span>
	                	<span class="icon-bar"></span>
	                	<span class="icon-bar"></span>
	                	<span class="icon-bar"></span>
	                </button>
	                <a class="navbar-brand" href="{% url 'welcome' %}"><img src="{% static 'images/header.png' %}"></a>
				</div>
				<div class="collapse navbar-collapse navbar-right">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'welcome' %}">Home</a></li>
						{% if request.user.is_authenticated %}
							<li><a href="{% url 'gallery:all_images' %}">Gallery</a></li>
							<li><a href="{% url 'gallery:new_gallery' %}">New Gallery</a></li>
							<li><a href="{% url 'accounts:gallery_logout' %}">Logout {{ request.user }}</a></li>
						{% else %}
							<li><a href="{% url 'accounts:gallery_login' %}">Login</a></li>
							<li><a href="{% url 'accounts:gallery_register' %}">Register</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
	</div>
	<!-- Main Block -->
	<div class="wrapper">
		{% block content %}
			
		{% endblock %}
	</div>
	<!-- Footer Part -->
	<nav class="navbar navbar-fixed-bottom">
		<div id="footer-part">
	    	<div class="container">
				<div class="row">
					<div class="col-md-12"> 
						<div class="footer-content wow bounceIn" data-wow-offset="0" data-wow-delay="0.5s">
							<h4> 2018 &copy; UrGallery Limited - All Rights Reserved</h4>
						</div>
					</div>
				</div>
			</div>
		</div>
	</nav>
	<!-- Javascript -->
	<script type="text/javascript" href="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/jquery.lightbox.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

templates/welcome.html
{% extends 'layout.html' %}

{% block content %}
<div id="welcome-part">
	<div class="container">
		<h2>Welcome To UrGallery</h2>
	</div>	
</div>
{% endblock %}